version: '3.8'
services:
 nginx:
   image: nginx:latest
   ports:
    - 80:80
   volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./htdocs:/var/www/html
   depends_on:
    - php
   restart: always

 php:
  build: ./php
  volumes:
   - ./htdocs:/var/www/html
  depends_on:
   - mysql
  restart: always

 mysql:
  build: ./mysql
  volumes:
   - db-data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  restart: always

 phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  environment:
   PMA_HOST: mysql
  ports:
   - 8080:80
  depends_on:
   - mysql
  restart: always

 mail:
  image: mailhog/mailhog
  ports:
   - 8025:8025

volumes:
 db-data:
